[package]
name = "kusto_gen_core"
version = "0.1.0"
edition = "2024"

[dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"
num-traits = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
walkdir = "2"
